### ISSUE TITLE
[Back] Sign auth challenge nonce

### ISSUE THREAD

**Issue by blukat29** [KAIST-IS521/TeamFive#27]
https://github.com/KAIST-IS521/2017-Spring/commit/5a4f5cc06d751f5e0af0a815641427e02e2c4b2b 을 반영한다.

**Comment by mikkang** [comment]
<pre>
Exception in thread Thread-15:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File
 "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/gnupg/_meta.py", line 650, in _read_response
    result._handle_status(keyword, value)
  File "/usr/local/lib/python3.6/site-packages/gnupg/_parsers.py", line 1715, in _handle_status
    super(Crypt, self)._handle_status(key, value)
  File "/usr/local/lib/python3.6/site-packages/gnupg/_parsers.py", line 1628, in _handle_status
    raise ValueError("Unknown status message: %r" % key)
ValueError: Unknown status message: 'KEY_CONSIDERED'
</pre>
기능은 잘 동작하는거 같은데, 위 에러 발생 버그 수정해야함

이거 어떻게 해결해야할지..ㅠ

**Comment by mikkang** [comment]
해결 ㅋ
gnupg 대신 python-gnupg 설치하니 잘 되네요.
